accounts/urls.py
from django.urls import path, re_path, include

app_name = 'accounts'

from rest_framework.routers import DefaultRouter

from accounts.views import *
from rest_framework.authtoken import views as rest_auth_views
from django.contrib.auth import views as auth_views
router = DefaultRouter()
router.register('profile', UserProfileViewSet) 

urlpatterns = [
    path('',include(router.urls)),
    # templates
    re_path(r'^index/$',dashboardView.as_view(),name='dashboardView'),
    re_path(r'login/$', auth_views.LoginView.as_view(template_name="accounts/login.html"),name="login"),
    re_path(r'logout/$', auth_views.LogoutView.as_view(), name="logout"),    
    re_path(r'signup/$', SignUp.as_view(), name="signup"),
    path('login/', UserLoginApiView.as_view()),
    path('api-token-auth/', rest_auth_views.obtain_auth_token, name='api-tokn-auth'), 
    
    path('product/<pk>/', ProductView.as_view(), name='product'),
    path('cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('cart-items/', CartItemsView.as_view(), name='cart-items'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('place-order/', PlaceOrderView.as_view(), name='place-order'),
    path('contact-us/', ContactUsView.as_view(), name='contact-us'),
    # API
    re_path(r'^api/products/$', ProductListAPIView.as_view(), name='products'),
    re_path(r'^api/products/(?P<pk>\d+)/$', ProductRetrieveAPIView.as_view(), name='product_detail'),    
    re_path(r'^api/orders/$', OrderListAPIView.as_view(), name='orders_api'),
    re_path(r'^api/orders/(?P<pk>\d+)/$', OrderRetrieveAPIView.as_view(), name='order_detail_api'),
]

super_store_project/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'', include('accounts.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django_countries.fields import CountryField
from django.urls  import reverse
class UserProfileManager(BaseUserManager):
    """Manager for user profiles"""
    def create_user(self, email, name, password=None):
        """Create a new user profile"""
        if not email:
            raise ValueError('User must have an email')
        email = self.normalize_email(email)
        user = self.model(email=email,name=name)

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self,email,name,password):
        """Create a new superuser with given details"""
        user = self.create_user(email,name,password)
        user.is_superuser =  True   #this is fetched from PermissionsMixin
        user.is_staff = True        #this is fetched from PermissionsMixin
        user.save(using=self._db)

        return user

class UserProfileInfo(AbstractBaseUser,PermissionsMixin):
    """Database model for user in the system"""
    email = models.EmailField(max_length=255, unique=True)  #no records with same email
    name = models.CharField(max_length=255)
    is_activated = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserProfileManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        """Retrieve full name of user"""
        return self.name

    def get_short_name(self):
        """Retrieve short name of user"""
        return self.name

    def __str__(self):
        """Return string representation of our user"""
        return self.email
    
class Product(models.Model):
    name = models.CharField(max_length=255) 
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='products')
    price = models.IntegerField() 

    def get_absolute_url(self):
        return reverse("accounts:product", kwargs={     # this will redirected to urls.py namespace = product
            "pk" : self.pk
        })
        
    def __str__(self):
        return self.name   

    def get_add_to_cart_url(self):
        return reverse("accounts:add-to-cart", kwargs={
            "pk" : self.pk
        })
        
@receiver(pre_delete, sender=Product)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.image.delete(False)

class OrderItem(models.Model):
    user = models.ForeignKey(UserProfileInfo,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"      
    def get_total_item_price(self):
        return self.quantity * self.product.price
        
class Order(models.Model):
    userprofileinfo = models.ForeignKey(UserProfileInfo,related_name='orders',on_delete=models.DO_NOTHING,)        
    products = models.ManyToManyField(OrderItem)
    ordered = models.BooleanField(default=False)
    def __str__(self):
        return self.userprofileinfo.name   
    def cal_total_amount(self):
        total = 0
        for order_item in self.products.all():
            total += order_item.get_total_item_price()
        return total  
        
class CheckoutAddress(models.Model):
    user = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    pin = models.CharField(max_length=100)

    def __str__(self):
        return self.user.name        

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT = (
    ('C', 'Credit Card'),
    ('U', 'UPI'),
    ('D', 'Debit card')
)
class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("email", "name", "password1")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].label = "Email"
class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Street Address'
    }))

    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Apartment'
    }))

    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
        'class': 'custom-select d-block w-100'
    }))
    
    pin = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))

    same_billing_address = forms.BooleanField(required=False)
    save_info = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT)

accounts/views.py
from rest_framework import viewsets, filters, generics
from rest_framework.authentication import TokenAuthentication, SessionAuthentication
import django_filters.rest_framework
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.settings import api_settings
from django.urls import reverse_lazy
from accounts import serializer, models, permissions
from django.views.generic import CreateView, ListView, DetailView, View, TemplateView
from .forms import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404,redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from . models import *

class dashboardView(ListView):
    model = Product
    template_name = "accounts/dashboard.html"

class ProductView(DetailView):
    model = Product
    template_name = "accounts/product.html"

class PlaceOrderView(TemplateView):
    template_name = 'accounts/thank_you.html'   

class ContactUsView(TemplateView):
    template_name = 'accounts/contact_us.html'

class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signup.html"
    
class UserProfileViewSet(viewsets.ModelViewSet):
    """Handle creating and updating profiles"""
    serializer_class = serializer.UserProfileSerializer
    queryset = UserProfileInfo.objects.all()
    
    # enable authentication; one user can modify only his details
    authentication_classes = (TokenAuthentication,)
    permission_classes = (permissions.UpdateOwnProfile,) #trigger has_object_permission function inside permissions.py file
    
    #searching of users
    filter_backends = (filters.SearchFilter,) 
    search_fields = ('name','email',)

class UserLoginApiView(ObtainAuthToken):
    """Handle creating user authentcation tokens"""
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES

class ProductListAPIView(generics.ListAPIView):
    #permission_classes = [IsAuthenticated]
    queryset = Product.objects.all()
    serializer_class = serializer.ProductSerializer
    filter_backends = [
                    filters.SearchFilter, 
                    filters.OrderingFilter, 
                    django_filters.rest_framework.DjangoFilterBackend,
                    ]
    search_fields = ["name", "description"]
    ordering_fields  = ["name", "id"]
    #filter_class = ProductFilter
    #pagination_class = ProductPagination


class ProductRetrieveAPIView(generics.RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = serializer.ProductDetailSerializer


class OrderRetrieveAPIView(generics.RetrieveAPIView):
    authentication_classes = [SessionAuthentication]
    #permission_classes = [IsOwnerAndAuth]
    model = Order
    queryset = Order.objects.all()
    serializer_class = serializer.OrderDetailSerializer

    def get_queryset(self, *args, **kwargs):
        return Order.objects.all() #filter(user__user=self.request.user)


class OrderListAPIView(generics.ListAPIView):
    authentication_classes = [SessionAuthentication]
    #permission_classes = [IsOwnerAndAuth]
    model = Order
    queryset = Order.objects.all()
    serializer_class = serializer.OrderDetailSerializer

    def get_queryset(self, *args, **kwargs):
        return Order.objects.all() #filter(user__user=self.request.userprofileinfo)

    def post(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


# Cart Views
@login_required
def add_to_cart(request, pk):
    """ 
    adding products from product.html to cart (Flow: models.py->urls.py->views.py(this function))
    """
    product = get_object_or_404(Product, pk=pk )
    order_item, created = OrderItem.objects.get_or_create(
        product = product,
        user = request.user,
        ordered = False
    )
    order_qs = Order.objects.filter(userprofileinfo=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        order.products.add(order_item)
        return redirect("accounts:cart-items")
    else: 
        order = Order.objects.create(userprofileinfo=request.user)
        order.products.add(order_item)
        return redirect("accounts:cart-items")
    
class CartItemsView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):

        try:
            order = Order.objects.get(userprofileinfo=self.request.user, ordered=False)
            context = {
                'object': order
            }
            print(order)
            return render(self.request, 'accounts/cart_items.html', context)
        except ObjectDoesNotExist:
            print("You do not have an order")
            return redirect("/")
            
class CheckoutView(View):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        order = Order.objects.get(userprofileinfo=self.request.user, ordered=False)
        context = {
            'form': form,
            'order': order
        }
        return render(self.request, 'accounts/checkout.html', context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        
        try:
            order = Order.objects.get(userprofileinfo=self.request.user, ordered=False)
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                pin = form.cleaned_data.get('pin')
                # TODO: add functionaly for these fields
                # same_billing_address = form.cleaned_data.get('same_billing_address')
                # save_info = form.cleaned_data.get('save_info')
                payment_option = form.cleaned_data.get('payment_option')

                checkout_address = CheckoutAddress(
                    user=self.request.user,
                    street_address=street_address,
                    apartment_address=apartment_address,
                    country=country,
                    pin=pin
                )
                checkout_address.save()
                order.checkout_address = checkout_address
                order.save()
                return redirect('accounts:place-order')


        except ObjectDoesNotExist:
           return redirect("accounts:cart-items")            

templates/accounts/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>Superstore</title>
  </head>
  <body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <div class="container">
		<a class="navbar-brand" href="#"><img src="">Superstore</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		
		<div class="collapse navbar-collapse" id="navbarNav">
		  <ul class="navbar-nav ms-auto">
			{% if user.is_authenticated %}
			<li class="nav-item">
			  <a class="nav-link active" aria-current="page" href="{% url 'accounts:dashboardView' %}">Hi {{user.name }},</a>
			</li>
			{% endif %}
			<li class="nav-item">
			  <a class="nav-link active" aria-current="page" href="{% url 'accounts:dashboardView' %}">Home</a>
			</li>
			{% if user.is_authenticated %}
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'accounts:logout' %}">Logout </a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'accounts:cart-items' %}">Cart </a>
			</li>
			{% else %}
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
			</li>	
			{% endif %}
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'accounts:contact-us' %}">Contact Us</a>
			</li>
		  </ul>
		</div>
	  </div>
	</nav>
	
	<div class="container mycontent">
	{% block content %}

	{% endblock %}
	</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </body>
</html>

templates/accounts/cart_items.html
{% extends 'accounts/base.html' %}

{% block content %}

<main>
    <div class= "container">
        <div class="table-responsive text-nowrap">
    <h3>
        <strong>Your Cart</strong>
    </h3>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.products.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.product.name }}</td>
            <td>
           &#8377;{{ order_item.product.price}}

            </td>
            <td>
            {{ order_item.quantity}}
            </td>
        </tr>

        {% empty %}
        <tr>
            <td colspan="4">Your cart is Empty</td>
        </tr>

         <tr>
            <td colspan="4">
                <a href="{% url 'accounts:dashboardView' %}" class="btn btn-primary float-right">Continue Shopping</a>
            </td>
        </tr>

        {% endfor %}

        {% if object.cal_total_amount %}
        <tr>
            <td colspan="2"><b>Total Order Price</b></td>
            <td>&#8377;{{ object.cal_total_amount }}</td>
        </tr>
         <tr>
            <td colspan="4">
                <a href="{% url 'accounts:checkout' %}" class="btn btn-success float-right ml-2">Checkout</a>
                <a href="{% url 'accounts:dashboardView' %}" class="btn btn-primary float-right">Continue Shopping</a>
            </td>
        </tr>
        
        {% endif %}
        
        </tbody>
    </table>

        </div>
    </div>
</main>

{% endblock content %}

templates/accounts/checkout.html
{% extends 'accounts/base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block content %}

<main >
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
            {% csrf_token %}
              <!--address-->
              <div class="md-form mb-5">
                {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                {{ form.apartment_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.country }}
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="pin">Pin</label>
                  {{ form.pin }}
                  <div class="invalid-feedback">
                    Pin code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input {% if form.same_billing_address.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>
             
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

          <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{ order.products.count }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            
            {% for order_item in order.products.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.product.name }}</h6>
                <small class="text-muted">{{ order_item.product.description }}</small>
              </div>
              <span class="text-muted">{{ order_item.cal_total_amount }}</span>
            </li>
            {% endfor %}
           

            {% comment %} <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$0</span>
            </li> {% endcomment %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (INR)</span>
              <strong>{{ order.cal_total_amount }}</strong>
            </li>
          </ul>
          <!-- Cart -->

        </div>

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/accounts/contact_us.html
{% extends 'accounts/base.html' %}
{% block title %}Thank you{% endblock %}
{% load bootstrap5 %}


{% block content %}
<div class="container vertical-center ">
    <h3>Super store<br/>
    Delhi<br/>
    Ph: +91-123 456 789</h3>


</div>
{% endblock %}

templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block title %}Login{% endblock %}
{% load bootstrap5 %}
{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
		{% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

templates/accounts/product.html
{% extends 'accounts/base.html' %}

{% block content %}

<!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">{{ object.get_label_display }}</span>
              </a>
            </div>

            <p class="lead">

            {% if object.discount_price %}
              <span class="mr-1">
              <del>&#8377;{{ object.price }}</del>
              </span>
              <span>&#8377;{{ object.discount_price }}</span>
            {% else %}
             <span>&#8377;{{ object.price }}</span>
            {% endif %}

            </p>

            <p class="lead font-weight-bold">{{ object.item_name }}</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}

            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" >Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

            {{ object.get_quantity_in_chart }}
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" >Remove From cart
                <i class="fas fa-trash ml-1"></i>
            </a>
           

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% block title %}Sign Up{% endblock %}
{% load bootstrap5 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}

templates/accounts/thank_you.html
{% extends 'accounts/base.html' %}
{% block title %}Thank you{% endblock %}
{% load bootstrap5 %}


{% block content %}
<div class="container">
    <h3>Thank you for shopping with us!</h3>
</div>
{% endblock %}